spring:
  mail: 
    host: mail.grupocore.net
    username: tecnologia@quintoimpacto.net
    password: XXX
    port: 564    
  datasource: 
    url: jdbc:mysql://localhost:3306/tinder?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    generate-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            ddl-auto: update
  thymeleaf:
    cache: false 
server:
  error:
    whitelabel:
      enabled: false
